export const intentDetectionFlowReturnCode = {
  INTENT_UN_CLEAR: 'INTENT_UN_CLEAR',
  INTENT_CONFIG_NOT_FOUND: 'INTENT_CONFIG_NOT_FOUND',
  INTENT_HANDLER_NOT_FOUND: 'INTENT_HANDLER_NOT_FOUND',
  GENERAL_QUESTION_FLOW: 'GENERAL_QUESTION_FLOW',
  INTENT_FOUND: 'INTENT_FOUND',
  NO_INTENT_IS_CONFIGURED: 'NO_INTENT_IS_CONFIGURED',
}
